### ISSUE TITLE
Cannot find module 'twilio'

### ISSUE THREAD

**Issue by LinqLover** [mmeisels/actions-email#4]
```
Run mmeisels/actions-email@v1.1
  with:
    emailToAddress: ***
    emailFromAddress: ***
    emailBody: some email title
  env:
    SENDGRID_API_KEY: ***
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'twilio'
Require stack:
- /home/runner/work/_actions/mmeisels/actions-email/v1.1/dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/mmeisels/actions-email/v1.1/dist/main.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/mmeisels/actions-email/v1.1/dist/main.js'
  ]
}
```

BTW: The action name listed in the market place (`mmeisels/action-send-an-email-@v1`) is invalid and does not match the name of the action in the marketplace (`twilio-sendgrid-email`).

**Comment by awakash** [comment]
I'm running into the same issues as above.

**Comment by IriW** [comment]
Same here

**Comment by kiruija** [comment]
same
